export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL'
export const CREATE_ORDER_RESET = 'CREATE_ORDER_RESET'

export const CREATE_ORDER_DETAILS_REQUEST = 'CREATE_ORDER_DETAILS_REQUEST'
export const CREATE_ORDER_DETAILS_SUCCESS = 'CREATE_ORDER_DETAILS_SUCCESS'
export const CREATE_ORDER_DETAILS_FAIL = 'CREATE_ORDER_DETAILS_FAIL'

export const CREATE_ORDER_PAYMENT_REQUEST = 'CREATE_ORDER_PAYMENT_REQUEST'
export const CREATE_ORDER_PAYMENT_SUCCESS = 'CREATE_ORDER_PAYMENT_SUCCESS'
export const CREATE_ORDER_PAYMENT_FAIL = 'CREATE_ORDER_PAYMENT_FAIL'
export const CREATE_ORDER_PAYMENT_RESET = 'CREATE_ORDER_PAYMENT_RESET'

export const ORDER_MINE_LIST_REQUEST= 'ORDER_MINE_LIST_REQUEST'
export const ORDER_MINE_LIST_SUCCESS= 'ORDER_MINE_LIST_SUCCESS'
export const ORDER_MINE_LIST_FAIL= 'ORDER_MINE_LIST_FAIL'

